name: 'IaC - Quality Check'

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [infrastrucutre/**]

defaults:
  run:
    working-directory: infrastrucutre

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: cdk diff
          uses: youyo/aws-cdk-github-actions@v2
          with:
            cdk_subcommand: 'diff'
            actions_comment: true
            working_dir: "infrastrucutre"
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CICD_IAC }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CICD_IAC }}
            AWS_DEFAULT_REGION: 'eu-central-1'