name: Dependabot auto-merge
on:
  workflow_run:
    workflows:
      - Frontend - Quality Check
      - graphql-endpoint - Quality Check
    types:
      - completed

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: |
          gh pr review --approve "PR_URL"
          gh pr merge --auto --merge "PR_URL"
          gh pr edit --add-label automerge "PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


