name: test_auto
on:
  workflow_run:
    workflows:
      - test
    types:
      - completed

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Enable auto-merge for Dependabot PRs
        run: |
          gh pr review --approve "PR_NUMBER"
          gh pr edit --add-label automerge "PR_NUMBER"
        env:
          PR_NUMBER: ${{github.event.workflow_run.pull_requests[0].number}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


