name: test_auto
on:
  workflow_run:
    workflows:
      - test
    types:
      - completed

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: |
          gh pr review --approve "PR_URL"
          gh pr edit --add-label automerge "PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


