name: 'Frontend - Build an Release'

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [frontend/**]

defaults:
  run:
    working-directory: frontend

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: "aws-actions/configure-aws-credentials@v1"
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CICD_WEB_APP }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CICD_WEB_APP }}
          aws-region: "eu-central-1"

      - uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "sandboxDomainUri"
          env_variable_name: "sandboxDomainUri"


      - uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "sandboxHostingBucketName"
          env_variable_name: "sandboxHostingBucketName"

      - name: pwd
        run: echo "${{ env.SANDBOXDOMAINURI }}"

      - name: Initialize Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - uses: jakejarvis/s3-sync-action@master
        name: Upload App to S3 Bucket
        with:
          args: --follow-symlinks --delete --cache-control max-age=3600
        env:
          AWS_S3_BUCKET: ${{ env.SANDBOXHOSTINGBUCKETNAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CICD_WEB_APP }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CICD_WEB_APP }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: build