name: 'Frontend - Quality Check'

on:
  pull_request:
    branches: [main]
    paths: [frontend/**]

jobs:
  qualtiy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/webapp-qa-re.yaml
        with:
          CODECOV_TOKEN: ${{  secrets.CODECOV_TOKEN  }}
