name: 'Frontend - Quality Check'

on:
  pull_request:
    branches: [main]
    paths: [frontend/**]

jobs:
  qualtiy-check:
    uses: ./.github/workflows/webapp-qa-re.yaml
    secrets:
      CODECOV_TOKEN: ${{  secrets.CODECOV_TOKEN  }}